import pandas as pd
from data_limpia.filtros.columnas_vacias_PBI import columnas_vacias_PBI
from data_limpia.filtros.columnas_vacias_lista_secciones import columnas_vacias_lista_sedes
from data_limpia.filtros.columnas_vacias_lista_sedes_datos import columnas_vacias_lista_sedes_datos
from data_limpia.filtros.regiones_listadas import regiones_listadas

# columnas_vacias_PBI()
# columnas_vacias_lista_sedes()
# columnas_vacias_lista_sedes_datos()
regiones_listadas()